export const LARGE_MONSTERS: String[] = [
  "Aknosom",
  "Almudron",
  "Anjanath",
  "Apex Arzuros",
  "Apex Diablos",
  "Apex Mizutsune",
  "Apex Rathalos",
  "Apex Rathian",
  "Apex Zinogre",
  "Arzuros",
  "Astalos",
  "Aurora Somnacanth",
  "Barioth",
  "Barroth",
  "Basarios",
  "Bazelgeuse",
  "Bishaten",
  "Blood Orange Bishaten",
  "Chameleos",
  "Chaotic Gore Magala",
  "Crimson Glow Valstrax",
  "Daimyo Hermitaur",
  "Diablos",
  "Espinas",
  "Flaming Espinas",
  "Furious Rajang",
  "Gaismagorm",
  "Garangolm",
  "Gold Rathian",
  "Gore Magala",
  "Goss Harag",
  "Great Baggi",
  "Great Izuchi",
  "Great Wroggi",
  "Jyuratodus",
  "Khezu",
  "Kulu-Ya-Ku",
  "Kushala Daora",
  "Lagombi",
  "Lucent Nargacuga",
  "Lunagaron",
  "Magma Almudron",
  "Magnamalo",
  "Malzeno",
  "Mizutsune",
  "Nargacuga",
  "Narwa the Allmother",
  "Pukei-Pukei",
  "Pyre Rakna-Kadaki",
  "Rajang",
  "Rakna-Kadaki",
  "Rathalos",
  "Rathian",
  "Risen Chameleos",
  "Risen Kushala Daora",
  "Risen Teostra",
  "Royal Ludroth",
  "Scorned Magnamalo",
  "Seething Bazelgeuse",
  "Seregios",
  "Shagaru Magala",
  "Shogun Ceanataur",
  "Silver Rathalos",
  "Somnacanth",
  "Teostra",
  "Tetranadon",
  "Thunder Serpent Narwa",
  "Tigrex",
  "Tobi-Kadachi",
  "Violet Mizutsune",
  "Volvidon",
  "Wind Serpent Ibushi",
  "Zinogre",
];

export const SMALL_MONSTERS: String[] = [
  "Altaroth",
  "Anteka",
  "Baggi",
  "Bnahabra",
  "Boggi",
  "Bombadgy",
  "Bullfango",
  "Ceanataur",
  "Delex",
  "Felyne",
  "Gajau",
  "Gargwa",
  "Gowngoat",
  "Hermitaur",
  "Hornetaur",
  "Izuchi",
  "Jaggi",
  "Jaggia",
  "Jagras",
  "Kelbi",
  "Kestodon",
  "Ludroth",
  "Melynx",
  "Popo",
  "Pyrantula",
  "Rachnoid",
  "Remobra",
  "Rhenoplos",
  "Slagtoth",
  "Uroktor",
  "Velociprey",
  "Vespoid",
  "Wroggi",
  "Zamite",
];
